apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
        - name: frontend
          image: malathi1898/calc_deployment_project:frontend
          ports:
            - containerPort: 80
        - name: backend
          image: malathi1898/calc_deployment_project:backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  selector:
    app: calc
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

