apiVersion: v1

kind: Pod

metadata:
  name: calc_deployment_project-pod-2
  labels: 
    project: calculator

spec:
  containers:
    - name: calc_deployment_project
      image: malathi1898/calc_deployment_project
      ports:
        - containerPort: 8080

