apiVersion: v1
kind: Pod
metadata:
  name: calc-pod-3
  labels:
    project: calculator
spec:
  containers:
    - name: calc-frontend
      image: malathi1898/calc_deployment_project:frontend
      ports:
        - containerPort: 80
    - name: calc-backend
      image: malathi1898/calc_deployment_project:backend
      ports:
        - containerPort: 8080

